#!/bin/sh
# ENV Vars (None anymore)

# ---------- Antigen ----------

# Load the oh-my-zsh's library
antigen use oh-my-zsh

#! Bundles & Plugins
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zpm-zsh/colors

# Powerlevel10k Theme - epic theme
antigen theme romkatv/powerlevel10k

antigen bundles <<EOBUNDLES

        # oh-my-zsh plugins
        git
        git-lfs
        github
        gitignore
        aliases
        command-not-found
        docker
        docker-compose
        emoji
        encode64
        thefuck
        copypath
        copyfile
        history
        dirhistory
        frontend-search
        jsontools
        node
        npm
        nvm
        pip
        python
        sfffe
        sprunge
        systemd
        ubuntu
        urltools
        # vscode
        yarn


        # Custom Plugins (Community)
        # Custom Plugins (Community)
        # Tarrasch/zsh-autoenv
        zpm-zsh/figures
        zpm-zsh/core-config
        zpm-zsh/helpers
        zpm-zsh/check-deps
        zpm-zsh/ls
        zpm-zsh/undollar
        # molovo/crash
        Cloudstek/zsh-plugin-appup
        unixorn/autoupdate-antigen.zshplugin
        MichaelAquilina/zsh-you-should-use
        # oz/safe-paste
        changyuheng/fz
        # mdumitru/fancy-ctrl-z
        oldratlee/hacker-quotes
        andyrichardson/zsh-node-path
        erikced/zsh-pyenv-lazy-load
        ntnyq/omz-plugin-pnpm
        momo-lab/zsh-abbrev-alias
        jirutka/zsh-shift-select

        # Always last for all autosuggestions possible
        zsh-users/zsh-autosuggestions
        

EOBUNDLES
#! End Bundles & Plugins

# Tell antigen that you're done
antigen apply
