#!/bin/sh
# ENV Vars (None anymore)

# ---------- Antigen ----------

# Load the oh-my-zsh's library
antigen use oh-my-zsh

#! Bundles & Plugins
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zpm-zsh/colors

antigen bundles <<EOBUNDLES

        # oh-my-zsh plugins
        git
        git-lfs
        github
        gh
        gitignore
        aliases
        command-not-found
        docker
        docker-compose
        emoji
        encode64
        thefuck
        copypath
        copyfile
        history
        dirhistory
        frontend-search
        jsontools
        node
        npm
        nvm
        pip
        python
        safe-paste
        sfffe
        sprunge
        systemd
        ubuntu
        urltools
        vscode
        yarn
        

        # Custom Plugins (Community)
        # Custom Plugins (Community)
        djui/alias-tips
        Tarrasch/zsh-autoenv
        zpm-zsh/helpers
        zpm-zsh/check-deps
        molovo/crash

        # Always last for all autosuggestions possible
        zsh-users/zsh-autosuggestions

EOBUNDLES
#! End Bundles & Plugins

# Powerlevel10k Theme - epic theme
antigen theme romkatv/powerlevel10k


# Tell antigen that you're done
antigen apply
