#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# export GH_TOKEN=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

# Source environment settings
source "$DOTZSH/env.zsh"

# Customize to your needs...

